---
# tasks file for ppp_amiga

- name: start ppp_amiga
  debug:
    msg: Start ppp_amiga

- name: install the required software
  package:
    name: "{{ item }}"
    state: present
  loop:
    - iptables-persistent
    - ppp

- name: copy the firewall
  template:
    src: etc/iptables/rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify:
    - restore firewall

- name: enable forwarding in the kernel
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    reload: yes
    state: present
    sysctl_set: yes

- name: copy the PPP peer file
  template:
    src: "{{ ppp_peers_dir }}/amiga.j2"
    dest: "/{{ ppp_peers_dir }}/amiga"
    owner: root
    group: dip
    mode: u=rw,g=r,o=
  notify:
    - restart ppp_amiga

- name: enable the pppd service
  template:
    src: etc/systemd/system/pppd@.service.j2
    dest: /etc/systemd/system/pppd@.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart ppp_amiga
